version: "3.6"
services:
  rundeck-database:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
        - rundeck_db:/var/lib/mysql
    networks:
      - rundeck_network
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_ROOT_PASSWORD: "rundeck"
      MYSQL_DATABASE: "rundeckdb"
      MYSQL_USER: "rundeck"
      MYSQL_PASSWORD: "rundeck"
  rundeck:
    build:
      context: ./rundeck
    ports:
      - "4440:4440"
    environment:
      DATABASE_URL: "jdbc:mysql://rundeck-database/rundeckdb?autoReconnect=true"
      RUNDECK_PASSWORD: "rundeck"
      DATABASE_ADMIN_USER: "root"
      DATABASE_ADMIN_PASSWORD: "rundeck"
      NO_LOCAL_MYSQL: "true"

    networks:
      - rundeck_network

networks:
  rundeck_network:
    driver: bridge

volumes:
  rundeck_db:
    driver: local